# -*- coding: utf-8 -*-
"""Pneumonia detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiAVpAbPQSrSaVLteCecGVfzl_NTv7EZ
"""

import os
import zipfile
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from IPython.display import display
import ipywidgets as widgets

# =========================
# 0. DOWNLOAD DATA (KAGGLE)
# =========================
os.system('kaggle datasets download -d paultimothymooney/chest-xray-pneumonia')

if os.path.exists("chest-xray-pneumonia.zip"):
    with zipfile.ZipFile("chest-xray-pneumonia.zip", 'r') as zip_ref:
        zip_ref.extractall(".")

print("✅ Dataset ready!")

# =========================
# 1. LOAD DATA
# =========================
train_dir = "chest_xray/train"
test_dir = "chest_xray/test"

datagen = ImageDataGenerator(rescale=1./255)

train_data = datagen.flow_from_directory(
    train_dir,
    target_size=(128, 128),
    color_mode='grayscale',
    batch_size=32,
    class_mode='binary'
)

test_data = datagen.flow_from_directory(
    test_dir,
    target_size=(128, 128),
    color_mode='grayscale',
    batch_size=32,
    class_mode='binary'
)

# =========================
# 2. BUILD MODEL
# =========================
model = tf.keras.Sequential([
    tf.keras.Input(shape=(128, 128, 1)),

    tf.keras.layers.Conv2D(16, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# =========================
# 3. TRAIN MODEL
# =========================
print("\n🚀 Training started...\n")

history = model.fit(
    train_data,
    epochs=10,
    validation_data=test_data
)

print("\n✅ Training complete!")

# =========================
# 4. SAVE MODEL
# =========================
#model.save("pneumonia_model.h5")
model.save("pneumonia_model.keras")
print("✅ Model saved!")

# =========================
# 5. LOAD MODEL (for inference)
# =========================
#model = load_model("pneumonia_model.h5")
model = load_model("pneumonia_model.keras")
print("✅ Model loaded!")

# =========================
# 6. IMAGE UPLOAD UI
# =========================
uploader = widgets.FileUpload(accept='image/*', multiple=False)
display(uploader)

# =========================
# 7. PREPROCESS FUNCTION
# =========================
def preprocess_image(file_path):
    img = image.load_img(file_path, target_size=(128, 128), color_mode='grayscale')
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img, img_array

# =========================
# 8. PREDICTION FUNCTION
# =========================
def predict_image(b):
    if len(uploader.value) == 0:
        print("❌ Please upload an image first.")
        return

    uploaded_file = list(uploader.value.values())[0]

    with open("temp.png", "wb") as f:
        f.write(uploaded_file['content'])

    img, img_array = preprocess_image("temp.png")

    prediction = model.predict(img_array)[0][0]

    # Show image
    plt.imshow(img, cmap='gray')
    plt.title("Uploaded X-ray")
    plt.axis('off')
    plt.show()

    # =========================
    # RESULT INTERPRETATION
    # =========================
    print("\n🔍 AI Analysis Result:")

    if prediction > 0.5:
        print(f"⚠️ High probability of Pneumonia ({prediction:.2f})")
        print("👉 The model detected patterns similar to pneumonia.")
    else:
        print(f"✅ Likely Normal ({1 - prediction:.2f})")
        print("👉 The model did not detect strong pneumonia patterns.")

    print("\n🧠 Explanation:")
    print("The AI analyzes lung textures, opacity, and structural patterns.")
    print("It compares your image with patterns learned during training.")

    print("\n⚠️ Disclaimer:")
    print("This is NOT a medical diagnosis. Consult a qualified doctor.")

# =========================
# 9. BUTTON
# =========================
button = widgets.Button(description="Analyze X-ray")
button.on_click(predict_image)

display(button)